apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: values-cert-manager-rancher-desktop
    files:
      - values.rancher-desktop.yaml
resources:
  - ../base
patches:
  - path: patch-helm-release.yaml
